/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/tool/index" |
       "/pages/index/index" |
       "/pages/about/about" |
       "/pages/gameTool/addGame" |
       "/pages/gameTool/gameRecords" |
       "/pages/gameTool/gameTool" |
       "/pages/help/help" |
       "/pages/history/history" |
       "/pages/index/info" |
       "/pages/tools/tools" |
       "/pages/user/user";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/tool/index" | "/pages/index/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
